"""Initial migration
Revision ID: 689e7c079359
Revises:
Create Date: 2025-04-25 13:04:14.778243
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = '689e7c079359'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_folder_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_path', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('is_auto_backup', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_file_source_folder_id', 'monitored_folder', ['source_folder_id'], ['id'])
    with op.batch_alter_table('file_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checksum', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('change_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_version', schema=None) as batch_op:
        batch_op.drop_column('change_reason')
        batch_op.drop_column('checksum')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('fk_file_source_folder_id', type_='foreignkey')
        batch_op.drop_column('is_auto_backup')
        batch_op.drop_column('source_path')
        batch_op.drop_column('source_folder_id')
    # ### end Alembic commands ###
